health_monitor_node:
  ros__parameters:
    topic_timeout_s: 5.0
    topics_to_monitor:
      - /lidar_points      # Placeholder for Lidar
      - /uwb/data     # Placeholder for UWB
      - /image_right_raw/h264_half # Placeholder for Camera
      - /rt/odom            # Placeholder for Odom
      - /rt/lowstate    # Placeholder for State Machine
      - /rl_lowcmd # Placeholder for Low Command from rl model
      - /joy # Placeholder for Joy